#!/usr/bin/env bash
# This script install nginx
# Update package lists
sudo apt-get update
# Install nginx
sudo apt-get install -y nginx
# Configure nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
# Display Hello World!
echo "Hello World!" > /var/www/html/index.html
# test
sudo nginx -t
# restart and reload 
sudo service nginx restart
sudo service nginx reload
